[package]
name = "any-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["fs", "io-util"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
